services:

  rabbitmq1:
    build:
      dockerfile: rabbitmq.Dockerfile
    container_name: rabbitmq1
    hostname: rabbitmq1
    networks:
      - rabbitnet
    environment:
      - RABBITMQ_ERLANG_COOKIE=${COMPOSE_PROJECT_NAME}

  rabbitmq2:
    build:
      dockerfile: rabbitmq.Dockerfile
    container_name: rabbitmq2
    hostname: rabbitmq2
    networks:
      - rabbitnet
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${COMPOSE_PROJECT_NAME}
    depends_on:
      - rabbitmq1

  rabbitmq3:
    build:
      dockerfile: rabbitmq.Dockerfile
    container_name: rabbitmq3
    hostname: rabbitmq3
    networks:
      - rabbitnet
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${COMPOSE_PROJECT_NAME}
    depends_on:
      - rabbitmq1

  haproxy:
    build:
      dockerfile: haproxy.Dockerfile
    container_name: haproxy
    hostname: haproxy
    networks:
      - rabbitnet
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672

networks:
  rabbitnet:
    driver: bridge