services:

  mongodb:
    image: mongodb/mongodb-community-server:latest
    hostname: mongodb
    container_name: mongodb
    entrypoint: ["/usr/bin/mongod","--bind_ip_all","--replSet","tr0"]
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - mongodbnet

  mongosetup:
    image: mongodb/mongodb-community-server:latest
    depends_on:
      - mongodb
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 10 && mongosh --host mongodb --port 27017 --eval 'rs.initiate()'"] 
    networks:
      - mongodbnet

volumes:
  mongodb:

networks:
  mongodbnet:
    driver: bridge