services:

  mongodb:
    build:      
      dockerfile: mongodb.Dockerfile
    hostname: mongodb
    extra_hosts:
      - "workdocker.localdomain:127.0.0.1"
    container_name: mongodb
    command: --bind_ip localhost,mongodb,workdocker.localdomain,0.0.0.0 --replSet rs0
    restart: unless-stopped
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    networks:
      - mongodbnet

  # https://hub.docker.com/_/mongo-express
  mongodb-express:
    image: mongo-express:latest
    hostname: mongodb-express
    container_name: mongodb-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb    
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 8081:8081
    networks:
      - mongodbnet

networks:
  mongodbnet:
    name: mongodbnet
    driver: bridge