services:

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    command: --bind_ip_all --replSet tr0
    restart: unless-stopped
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    networks:
      - mongodbnet
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongodb-express:
    image: mongo-express:latest
    hostname: mongodb-express
    container_name: mongodb-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
#    depends_on:
#      mongodb:
#        condition: service_healthy
    ports:
      - 8081:8081
    networks:
      - mongodbnet

networks:
  mongodbnet:
    name: mongodbnet
    driver: bridge